SELECT 
CASE
    WHEN (SELECT COUNT(DISTINCT Salary) FROM Employee)<=1 THEN NULL
    ELSE (SELECT Salary FROM Employee ORDER BY Salary DESC OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY)
END as SecondHIghestSalary;
